SELECT AU.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY, SUM(BS.SALES * B.PRICE) AS TOTAL_SALES
FROM BOOK B JOIN AUTHOR AU 
ON B.AUTHOR_ID = AU.AUTHOR_ID
JOIN BOOK_SALES BS
ON B.BOOK_ID = BS.BOOK_ID
WHERE DATE_FORMAT(BS.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY AU.AUTHOR_ID, AU.AUTHOR_NAME, B.CATEGORY
ORDER BY AU.AUTHOR_ID ASC, B.CATEGORY DESC;