SELECT ID, 
       COALESCE(CHILD_COUNT, 0) AS CHILD_COUNT
FROM (
    SELECT DISTINCT ID FROM ECOLI_DATA
) AS ALL_IDS
LEFT JOIN (
    SELECT PARENT_ID, COUNT(ID) AS CHILD_COUNT
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NOT NULL
    GROUP BY PARENT_ID
) AS CHILDREN_COUNT ON ALL_IDS.ID = CHILDREN_COUNT.PARENT_ID
ORDER BY ID ASC;