WITH GROUP_DATA AS(
    SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO
    GROUP BY FOOD_TYPE
)

SELECT RI.FOOD_TYPE, RI.REST_ID, RI.REST_NAME, GD.FAVORITES
FROM REST_INFO RI JOIN GROUP_DATA GD
ON RI.FAVORITES = GD.FAVORITES
AND RI.FOOD_TYPE = GD.FOOD_TYPE
ORDER BY FOOD_TYPE DESC;

# 한식 은돼지식당, 일식 스시사카우스, 중식 만정, 분식 애플우스, 양식 따띠따띠뜨