
SELECT FLAVOR
FROM(
        SELECT FH.FLAVOR, SUM(FH.TOTAL_ORDER) AS TOTAL
        FROM FIRST_HALF FH JOIN JULY JL
        ON FH.FLAVOR = JL.FLAVOR
        GROUP BY FLAVOR
        ORDER BY TOTAL DESC
        LIMIT 3
) A;