SELECT 
    CAST(DATE_FORMAT(D1.DIFFERENTIATION_DATE, '%Y') AS UNSIGNED) AS YEAR,
    MAX_D.SIZE_OF_COLONY - D1.SIZE_OF_COLONY AS YEAR_DEV,
    D1.ID
FROM ECOLI_DATA D1
JOIN (
    SELECT 
        DATE_FORMAT(DIFFERENTIATION_DATE, '%Y') AS YEAR,
        MAX(SIZE_OF_COLONY) AS SIZE_OF_COLONY
    FROM ECOLI_DATA
    WHERE DIFFERENTIATION_DATE IS NOT NULL
    GROUP BY DATE_FORMAT(DIFFERENTIATION_DATE, '%Y')
) AS MAX_D
ON DATE_FORMAT(D1.DIFFERENTIATION_DATE, '%Y') = MAX_D.YEAR
WHERE D1.DIFFERENTIATION_DATE IS NOT NULL
ORDER BY YEAR ASC, YEAR_DEV ASC;
