WITH JOIN_TABLE AS( SELECT FN.FISH_NAME
                    FROM FISH_INFO FI JOIN FISH_NAME_INFO FN
                    ON FI.FISH_TYPE = FN.FISH_TYPE)
                    
SELECT COUNT(*) AS FISH_COUNT
FROM JOIN_TABLE
WHERE FISH_NAME = 'BASS' OR FISH_NAME = 'SNAPPER';