WITH Ranked AS (
    SELECT ID, FISH_TYPE, LENGTH,
         ROW_NUMBER() OVER (PARTITION BY FISH_TYPE ORDER BY LENGTH DESC, ID ASC) AS rn
    FROM FISH_INFO
)

SELECT R.ID, FN.FISH_NAME, R.LENGTH
FROM FISH_NAME_INFO FN JOIN Ranked R
ON FN.FISH_TYPE = R.FISH_TYPE
WHERE R.rn = 1
ORDER BY R.ID ASC;
