WITH SCORE_SUM AS (
    SELECT E.EMP_NO,E.EMP_NAME,E.POSITION,E.EMAIL,SUM(G.SCORE) AS TOTAL_SCORE
    FROM HR_EMPLOYEES E
    JOIN HR_GRADE G ON E.EMP_NO = G.EMP_NO
    WHERE G.YEAR = 2022
    GROUP BY E.EMP_NO, E.EMP_NAME, E.POSITION, E.EMAIL
)

SELECT 
    TOTAL_SCORE AS SCORE,EMP_NO,EMP_NAME,POSITION,EMAIL
FROM SCORE_SUM
WHERE TOTAL_SCORE = (
    SELECT MAX(TOTAL_SCORE) FROM SCORE_SUM
);
