
WITH GROUP_DATA AS(
    SELECT B.CATEGORY AS CATEGORY, SUM(BS.SALES) AS TOTAL_SALES
    FROM BOOK B JOIN BOOK_SALES BS
    ON B.BOOK_ID = BS.BOOK_ID
    WHERE DATE_FORMAT(BS.SALES_DATE,'%Y-%m') = '2022-01'
    GROUP BY BS.BOOK_ID
)

SELECT CATEGORY, SUM(TOTAL_SALES) AS TOTAL_SALES
FROM GROUP_DATA
GROUP BY CATEGORY
ORDER BY CATEGORY ASC;